# Generated by Django 2.2 on 2019-04-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='donator',
            field=models.ForeignKey(limit_choices_to={'is_volunter': 'N'}, on_delete=django.db.models.deletion.CASCADE, to='foodApp.Profile'),
        ),
    ]
