# Generated by Django 2.2 on 2019-04-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_auto_20190418_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
