# Generated by Django 2.2 on 2019-04-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0004_auto_20190418_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_area', models.CharField(max_length=100)),
                ('beneficent', models.PositiveSmallIntegerField(default=0)),
                ('donator', models.ForeignKey(limit_choices_to={'volunter': 'N'}, on_delete=django.db.models.deletion.CASCADE, to='foodApp.FoodRequest')),
                ('volunter', models.ForeignKey(limit_choices_to={'volunter': 'Y'}, on_delete=django.db.models.deletion.CASCADE, to='foodApp.Profile')),
            ],
        ),
    ]
