# Generated by Django 2.2 on 2019-04-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0005_donatedfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedfood',
            name='volunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.Profile'),
        ),
    ]
