# Generated by Django 2.2 on 2019-04-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0006_auto_20190419_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatedfood',
            name='donator',
        ),
    ]
